
class Config {

 //   static client_id="543XCRHEDCJN5YQIZONCQ1NR0O3JWIYCFSWS4EKPPZMRPX3U";
  // static  client_secret = "GUAGXWWAQXHWBJQKLQ3QY5BIWXTF2VWBBHKX10QRLEIOGDBX";
    static gmapAPI="AIzaSyA4mGbTg2azsVzhvMhPRY8pTht8HAcD-5g";
    static client_id="FV0MWNX2GAQGJDXOKJKTNBO1UEWTVJCV5DXPSYA5RL0ZKFJO";
    static client_secret="QM0FBYMIUBXDIIAGHKA2PHEX0SIRNNHEXKWB2AURQO5O5O5S"

}
export default Config;